name: Build And Formatting Check.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  isSrcFormatted:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "./src"
          clangFormatVersion: 13

  isTestFormatted:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: "./test"
          clangFormatVersion: 13

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build .
